Website/views/amountUnavailable.py
# views/amountUnavailable.py
from flask import Blueprint, render_template

amountUnavailable_bp = Blueprint("amountUnavailable", __name__)


@amountUnavailable_bp.route("/amountUnavailable/<int:bankpas_id>")
def amountUnavailable(bankpas_id):
    """
    Render the amountUnavailable.html template when the route is accessed.
    """
    return render_template("amountUnavailable.html", bankpas_id=bankpas_id)

Website/views/bePatient.py
# views/bePatient.py
from flask import Blueprint, render_template, request
from models import Bankpassen, Rekeningen, Biljetten, Transacties
from db import db
import serial
from datetime import datetime, date

# Start serial communication
arduino_uno = serial.Serial("/dev/ttyACM1", 9600)  # Update with your Mega's device name


bePatient_bp = Blueprint("bePatient", __name__)


@bePatient_bp.route("/bepatientamount/<int:bankpas_id>", methods=["GET", "POST"])
def bePatientAmount(bankpas_id):
    if request.method == "POST":
        if request.form["amount"] != "":
            bills = []
            amount_to_withdraw = int(request.form["amount"])
            if amount_to_withdraw % 10 != 0:
                print("Pin more money")
            else:
                bankpas = Bankpassen.query.get(bankpas_id)
                if not bankpas:
                    return "Bankpassen not found"

                rekening_nummer = bankpas.rekening_nummer

                rekening = Rekeningen.query.get(rekening_nummer)
                if not rekening:
                    return "Rekeningen not found"

                current_balance = rekening.balans
                if current_balance < amount_to_withdraw:
                    return render_template(
                        "amountUnavailable.html", bankpas_id=bankpas_id
                    )

                new_balance = current_balance - amount_to_withdraw
                rekening.balans = new_balance
                transactie = Transacties(
                    datum=date.today(),
                    tijd=datetime.now().time(),
                    locatie="CHF",  # Update as necessary
                    type="Withdrawal",
                    hoeveelheid=amount_to_withdraw,
                    bankpas_id=bankpas_id,
                    rekening_nummer=rekening.rekening_nummer,
                )
                db.session.add(transactie)
                while amount_to_withdraw != 0:
                    totalFifty = Biljetten.query.get(50).hoeveelheid
                    fifty = Biljetten.query.get(50)
                    totalTwenty = Biljetten.query.get(20).hoeveelheid
                    twenty = Biljetten.query.get(20)
                    totalTen = Biljetten.query.get(10).hoeveelheid
                    ten = Biljetten.query.get(10)
                    if amount_to_withdraw > Biljetten.total_value():
                        return render_template(
                            "amountUnavailable.html", bankpas_id=bankpas_id
                        )
                    else:
                        if (
                            amount_to_withdraw >= 50
                            and Biljetten.query.get(50).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 50
                            fifty.hoeveelheid = totalFifty - 1
                            bills.append(50)
                            db.session.commit()
                        elif (
                            amount_to_withdraw >= 20
                            and Biljetten.query.get(20).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 20
                            twenty.hoeveelheid = totalTwenty - 1
                            bills.append(20)
                            db.session.commit()
                        elif (
                            amount_to_withdraw >= 10
                            and Biljetten.query.get(10).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 10
                            ten.hoeveelheid = totalTen - 1
                            bills.append(10)
                            db.session.commit()
            arduino_uno.write(str(bills).encode())
            return render_template("bePatient.html", bankpas_id=bankpas_id)
    return render_template("goodBye.html")


@bePatient_bp.route("/bepatientotheramount/<int:bankpas_id>", methods=["GET", "POST"])
def bePatientOtherAmount(bankpas_id):
    if request.method == "POST":
        bills = []
        if request.form["other_amount"] != "":
            amount_to_withdraw = int(request.form["other_amount"])
            if amount_to_withdraw % 10 != 0:
                print("Pin more money")
            else:
                # Retrieve the account number associated with the bankpas_id
                bankpas = Bankpassen.query.get(bankpas_id)
                if bankpas is None:
                    return "INVALID BANKPAS ID"

                rekening_nummer = bankpas.rekening_nummer

                # Retrieve the current balance of the account
                rekening = Rekeningen.query.get(rekening_nummer)
                if rekening is None:
                    return "INVALID REKENING NUMMER"

                current_balance = rekening.balans

                if current_balance < amount_to_withdraw:
                    return render_template(
                        "amountUnavailable.html", bankpas_id=bankpas_id
                    )
                new_balance = current_balance - amount_to_withdraw

                # Update the balance of the account after withdrawal
                rekening.balans = new_balance
                transactie = Transacties(
                    datum=date.today(),
                    tijd=datetime.now().time(),
                    locatie="CHF",  # Update as necessary
                    type="Withdrawal",
                    hoeveelheid=amount_to_withdraw,
                    bankpas_id=bankpas_id,
                    rekening_nummer=rekening.rekening_nummer,
                )
                db.session.add(transactie)
                db.session.commit()
                while amount_to_withdraw != 0:
                    totalFifty = Biljetten.query.get(50).hoeveelheid
                    fifty = Biljetten.query.get(50)
                    totalTwenty = Biljetten.query.get(20).hoeveelheid
                    twenty = Biljetten.query.get(20)
                    totalTen = Biljetten.query.get(10).hoeveelheid
                    ten = Biljetten.query.get(10)
                    if amount_to_withdraw > Biljetten.total_value():
                        return render_template(
                            "amountUnavailable.html", bankpas_id=bankpas_id
                        )
                    else:
                        if (
                            amount_to_withdraw >= 50
                            and Biljetten.query.get(50).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 50
                            fifty.hoeveelheid = totalFifty - 1
                            bills.append(50)
                            db.session.commit()

                        elif (
                            amount_to_withdraw >= 20
                            and Biljetten.query.get(20).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 20
                            twenty.hoeveelheid = totalTwenty - 1
                            bills.append(20)
                            db.session.commit()

                        elif (
                            amount_to_withdraw >= 10
                            and Biljetten.query.get(10).hoeveelheid > 0
                        ):
                            amount_to_withdraw -= 10
                            ten.hoeveelheid = totalTen - 1
                            bills.append(10)
                            db.session.commit()
            arduino_uno.write(str(bills).encode())
            return render_template("bePatient.html", bankpas_id=bankpas_id)
        return render_template("goodBye.html")


@bePatient_bp.route("/bepatientnewpin/<int:bankpas_id>", methods=["GET", "POST"])
def bePatientNewPin(bankpas_id):
    if request.method == "POST":
        if request.form["change_pin"] != "":
            newPin = request.form["change_pin"]
            bankpas = Bankpassen.query.get(bankpas_id)
            if not bankpas:
                return "Bankpassen not found"

            bankpas.pin_code = newPin
            db.session.commit()

            return render_template("goodBye.html", bankpas_id=bankpas_id)

    return render_template("goodBye.html")

Website/views/bePatientReceipt.py
# views/bePatientReceipt.py
from flask import Blueprint, render_template
from models import Transacties, Bankpassen
from sqlalchemy import desc
import serial
import time

bePatientReceipt_bp = Blueprint("bePatientReceipt", __name__)


def generate_receipt(transaction, account):
    # Build the receipt text
    receipt_text = "-------------------------------\n"
    receipt_text += "JinhangBank Withdrawal Receipt\n"
    receipt_text += "-------------------------------\n"
    receipt_text += f"Date: {transaction.datum}\n"
    receipt_text += f"Time: {transaction.tijd}\n"
    receipt_text += f"Location: {transaction.locatie}\n"
    receipt_text += f"Transaction Type: {transaction.type}\n"
    receipt_text += f"Withdrawal Amount: {transaction.hoeveelheid}\n"
    receipt_text += f"Account Number: {account.rekening_nummer}\n"
    receipt_text += "-------------------------------\n"
    receipt_text += "Thank you for using our services.\n"
    receipt_text += "-------------------------------\n"

    return receipt_text


@bePatientReceipt_bp.route("/bePatientReceipt/<int:bankpas_id>")
def bePatientReceipt(bankpas_id):
    """
    Render the bePatientReceipt.html template when the route is accessed.
    """
    most_recent_transaction = Transacties.query.filter(
        Transacties.bankpas_id == bankpas_id
    ).last()
    account = Bankpassen.query.get(bankpas_id)
    # Print the receipt with the most recent transaction details
    receipt_text = generate_receipt(most_recent_transaction, account)

    ser = serial.Serial("/dev/serial0", 19200, timeout=1)  # initialize the printer
    ser.write(bytearray([0x1B, 0x40]))  # Wake the printer
    time.sleep(0.5)
    ser.write(receipt_text.encode())  # Print the receipt
    ser.write(bytearray([0x1B, 0x64, 0x03]))  # Feed three lines
    ser.close()  # Close the printer connection

    return render_template("bePatientReceipt.html", bankpas_id=bankpas_id)

Website/views/blocked.py
# views/blocked.py
from flask import Blueprint, render_template

blocked_bp = Blueprint("blocked", __name__)


@blocked_bp.route("/blocked/<int:bankpas_id>")
def blocked(bankpas_id):
    """
    Render the blocked.html template when the route is accessed.
    """
    return render_template("blocked.html", bankpas_id=bankpas_id)

Website/views/changePin.py
# views/changePin.py
from flask import Blueprint, render_template

changePin_bp = Blueprint("changePin", __name__)


@changePin_bp.route("/changePin/<int:bankpas_id>")
def changePin(bankpas_id):
    """
    Render the changePin.html template with the provided bankpas_id when the route is accessed.
    """
    return render_template("changePin.html", bankpas_id=bankpas_id)

Website/views/chooseAmount.py
# views/chooseAmount.py
from flask import Blueprint, render_template

chooseAmount_bp = Blueprint("chooseAmount", __name__)


@chooseAmount_bp.route("/chooseAmount/<int:bankpas_id>", methods=["GET", "POST"])
def chooseAmount(bankpas_id):
    """
    Render the chooseAmount.html template with the provided bankpas_id when the route is accessed.
    """
    return render_template("chooseAmount.html", bankpas_id=bankpas_id)

Website/views/enterAmount.py
# views/enterAmount.py
from flask import Blueprint, render_template

enterAmount_bp = Blueprint("enterAmount", __name__)


@enterAmount_bp.route("/enterAmount/<int:bankpas_id>")
def enterAmount(bankpas_id):
    """
    Render the enterAmount.html template when the route is accessed.
    """
    return render_template("enterAmount.html", bankpas_id=bankpas_id)

Website/views/enterPin.py
# views/enterPin.py
from flask import Blueprint, render_template, request

enterPin_bp = Blueprint("enterPin", __name__)


@enterPin_bp.route("/enterPin")
def enterPin():
    """
    Render the enterPin.html template with the provided bankpas_id or redirect to scanCard.html if bankpas_id is not provided.
    """
    bankpas_id = request.args.get("bankpas_id", None)

    if bankpas_id is None:
        return render_template("scanCard.html")

    return render_template("enterPin.html", bankpas_id=bankpas_id)

Website/views/goodBye.py
# views/goodBye.py
from flask import Blueprint, render_template

goodBye_bp = Blueprint("goodBye", __name__)


@goodBye_bp.route("/goodBye")
def goodBye():
    """
    Render the goodBye.html template when the route is accessed.
    """
    return render_template("goodBye.html")

Website/views/makeChoice.py
# views/makeChoice.py
from flask import Blueprint, render_template

makeChoice_bp = Blueprint("makeChoice", __name__)


@makeChoice_bp.route("/makeChoice/<int:bankpas_id>")
def makeChoice(bankpas_id):
    """
    Render the makeChoice.html template with the provided bankpas_id when the route is accessed.
    """
    return render_template("makeChoice.html", bankpas_id=bankpas_id)

Website/views/pickLanguage.py
# views/pickLanguage.py
from flask import Blueprint, render_template

pickLanguage_bp = Blueprint("pickLanguage", __name__)


@pickLanguage_bp.route("/pickLanguage")
def pickLanguage():
    """
    Render the pickLanguage.html template when the route is accessed.
    """
    return render_template("pickLanguage.html")

Website/views/receiptChoice.py
# views/receiptChoice.py
from flask import Blueprint, render_template

receiptChoice_bp = Blueprint("receiptChoice", __name__)


@receiptChoice_bp.route("/receiptChoice/<int:bankpas_id>")
def receiptChoice(bankpas_id):
    """
    Render the receiptChoice.html template when the route is accessed.
    """
    return render_template("receiptChoice.html", bankpas_id=bankpas_id)

Website/views/scanCard.py
# views/scanCard.py
from flask import Blueprint, render_template

scanCard_bp = Blueprint("scanCard", __name__)


@scanCard_bp.route("/")
def scanCard():
    """
    Render the scanCard.html template when the route is accessed.
    """
    return render_template("scanCard.html")

Website/views/showBalance.py
# views/showBalance.py
from flask import Blueprint, render_template
from models import Bankpassen, Rekeningen

showBalance_bp = Blueprint("showBalance", __name__)


@showBalance_bp.route("/showBalance/<int:bankpas_id>")
def showBalance(bankpas_id):
    """
    Retrieve the balance of the account associated with the bankpas_id and render the showBalance.html template.
    """
    bankpas = Bankpassen.query.get(bankpas_id)
    rekening = Rekeningen.query.get(bankpas.rekening_nummer)
    return render_template("showBalance.html", balans=rekening.balans)

Website/views/takeMoney.py
# views/takeMoney.py
from flask import Blueprint, render_template

takeMoney_bp = Blueprint("takeMoney", __name__)


@takeMoney_bp.route("/takeMoney/<int:bankpas_id>")
def takeMoney(bankpas_id):
    """
    Render the takeMoney.html template when the route is accessed.
    """
    return render_template("takeMoney.html", bankpas_id=bankpas_id)

Website/views/takeReceipt.py
# views/takeReceipt.py
from flask import Blueprint, render_template

takeReceipt_bp = Blueprint("takeReceipt", __name__)


@takeReceipt_bp.route("/takeReceipt/<int:bankpas_id>")
def takeReceipt(bankpas_id):
    """
    Render the takeReceipt.html template when the route is accessed.
    """
    return render_template("takeReceipt.html", bankpas_id=bankpas_id)

Website/templates/amountUnavailable.html
<!-- amountUnavailable.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amount Unavailable</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
</head>
<body class="amountUnavailableBody">
    <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
        <button data-translate="quit" type="submit"></button>
    </form>
    <button data-translate="goBack" onclick="goBack()"></button>
    <script>
        function goBack() {
        window.history.back();
        }
    </script>
    <h1 data-translate="unavailable"></h1>
</body>
</html>

Website/templates/bePatient.html
<!-- bePatient.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Background Image</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
</head>
<body class="bePatientBody">
    <h1 data-translate="pleaseBePatient"></h1>
    <script>
        setTimeout(function() {
            window.location.href = "{{ url_for('takeMoney.takeMoney', bankpas_id=bankpas_id) }}";
        }, 5000);
    </script>
</body>
</html>

Website/templates/bePatientReceipt.html
<!-- bePatientReceipt.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Background Image</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
</head>
<body class="bePatientBody">
    <h1 data-translate="pleaseBePatient"></h1>
    <script>
        setTimeout(function() {
            window.location.href = "{{ url_for('takeReceipt.takeReceipt', bankpas_id=bankpas_id) }}";
        }, 5000);
    </script>
</body>
</html>

Website/templates/blocked.html
<!-- goodBye.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
</head>
<body class="blockedBody">
    <h1 class="" data-translate="blockedCard"></h1>
</body>
<script>
    setTimeout(function() {
        window.location.href = "{{ url_for('scanCard.scanCard') }}";
    }, 5000);
</script>
</html>

Website/templates/changePin.html
<!-- changePin.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navButtonsChoice.js') }}"></script>
    <script src="{{ url_for('static', filename='js/numPadChangePin.js') }}"></script>
</head>
<body class="changePinBody">
    <h1 data-translate="newPin"></h1>
    <div class="quitItemEnterPin">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="quit" type="submit"></button>
        </form>
    </div>
    <div class="enterAmountForm">
        <form action="{{ url_for('bePatient.bePatientNewPin', bankpas_id=bankpas_id) }}" method="POST">
            <input autofocus="true" type="password" id="change_pin" name="change_pin" required>
            <input type="hidden" name="amount" value="">
            <button type="submit"></button>
        </form>
    </div>
    <div class="goBackItem">
        <button onclick="goBack()"></button>
    </div>
    <h3 data-translate="pressOK"></h3>
    <script>
        function goBack() {
        window.history.back();
        }
    </script>
</body>
</html>

Website/templates/chooseAmount.html
<!-- chooseAmount.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Background Image</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navButtonsAmount.js') }}"></script>
</head>
<body class="chooseAmountBody">
    <div class="otherAmount">
        <form action="{{ url_for('enterAmount.enterAmount', bankpas_id=bankpas_id) }}" method="GET">
            <button data-translate="otherAmount" type="submit"></button>
        </form>
    </div>
    <div class="chooseAmount20">
        <form action="{{ url_for('bePatient.bePatientAmount', bankpas_id=bankpas_id) }}" method="POST">
            <input type="hidden" name="input_text" value="">
            <input type="hidden" name="amount" id="amount" value="20">
            <button type="submit"></button>
        </form>
    </div>
    <div class="chooseAmount50">
        <form action="{{ url_for('bePatient.bePatientAmount', bankpas_id=bankpas_id) }}" method="POST">
            <input type="hidden" name="input_text" value="">
            <input type="hidden" name="amount" id="amount" value="50">
            <button type="submit"></button>
        </form>
    </div>
    <div class="chooseAmount70">
        <form action="{{ url_for('bePatient.bePatientAmount', bankpas_id=bankpas_id) }}" method="POST">
            <input type="hidden" name="input_text" value="">
            <input type="hidden" name="amount" id="amount" value="70">
            <button type="submit"></button>
        </form>
    </div>
    <div class="chooseAmount100">
        <form action="{{ url_for('bePatient.bePatientAmount', bankpas_id=bankpas_id) }}" method="POST">
            <input type="hidden" name="input_text" value="">
            <input type="hidden" name="amount" id="amount" value="100">
            <button type="submit"></button>
        </form>
    </div>
    <div class="goBackItem">
        <button onclick="goBack()"></button>
    </div>
    <div class="quitItemChooseAmount">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="quit" type="submit"></button>
        </form>
    </div>
    <script>
        function goBack() {
        window.history.back();
        }
    </script>
</body>
</html>

Website/templates/enterAmount.html
 <!-- enterAmount.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Background Image</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>    
    <script src="{{ url_for('static', filename='js/numPadOtherAmount.js') }}"></script>
</head>
<body class="enterAmountBody">
    <div class="quitItemEnterPin">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="quit" type="submit"></button>
        </form>
    </div>
    <div class="goBackItem">
        <button onclick="goBack()"></button>
    </div>
    <div class="enterAmountForm">
        <form action="{{ url_for('bePatient.bePatientOtherAmount', bankpas_id=bankpas_id) }}" method="POST">
            <input autofocus="true" type="text" id="other_amount" name="other_amount" required>
            <input type="hidden" name="amount" value="">
            <button type="submit"></button>
        </form>
    </div>
    <h1>Enter Amount:</h1>
    <p>Minimal €10</p>
    <h3>Press OK to continue</h3>    
    <script>
        function goBack() {
        window.history.back();
        }
    </script>
</body>
</html>

Website/templates/makeChoice.html
<!-- makeChoice.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navButtonsChoice.js') }}"></script>
</head>
<body class="makeChoiceBody">
    <div class="showBalanceForm">
        <form action="{{ url_for('showBalance.showBalance', bankpas_id=bankpas_id) }}" method="GET">
            <button data-translate="showBalance" type="submit"></button>
        </form>
    </div>
    <div class="withdrawMoneyForm">
        <form action="{{ url_for('chooseAmount.chooseAmount', bankpas_id=bankpas_id) }}" method="GET">
            <button data-translate="withdrawMoney" type="submit"></button>
        </form>
    </div>
    <div class="changePinForm">
        <form action="{{ url_for('changePin.changePin', bankpas_id=bankpas_id) }}" method="GET">
            <button data-translate="changePin" type="submit"></button>
        </form>
    </div>
    <div class="quitItemEnterPin">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="quit" type="submit"></button>
        </form>
    </div>
    <div class="goBackItem">
        <button onclick="goBack()"></button>
    </div>
    <script>
    function goBack() {
    window.history.back();
    }
    </script>
    <h1 class="makeChoiceText" data-translate="makeAChoice"></h1>
</body>
</body>
</html>

Website/templates/pickLanguage.html
<!-- pickLanguage.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navPickLanguage.js') }}"></script>
</head>
<body class="pickLanguageBody">
    <div class="languageChange">
        <h1 data-translate="chooseYourLanguage"></h1>
    </div>
    <div class="nederlandsItem">
        <form action="{{ url_for('scanCard.scanCard') }}" method="GET">
            <button onclick="changeLanguage('nl')"></button>
        </form>
    </div>
    <div class="englishItem">
        <form action="{{ url_for('scanCard.scanCard') }}" method="GET">
            <button onclick="changeLanguage('en')"></button>
        </form>
    </div>
    <div class="deutschItem">
        <form action="{{ url_for('scanCard.scanCard') }}" method="GET">
            <button onclick="changeLanguage('de')"></button>
        </form>
    </div>
    <div class="francaisItem">
        <form action="{{ url_for('scanCard.scanCard') }}" method="GET">
            <button onclick="changeLanguage('fr')"></button>
        </form>
    </div>
    <div class="quitItem">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="quit" type="submit"></button>
        </form>
    </div>
    <div class="goBackItem">
        <button onclick="goBack()"></button>
    </div>
    <script>
    function goBack() {
    window.history.back();
    }
    </script>
</body>
</body>
</html>

Website/templates/receiptChoice.html
<!-- receiptChoice.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/translations.js') }}"></script>
    <script src="{{ url_for('static', filename='js/receiptNav.js') }}"></script>
</head>
<body class="receiptChoiceBody">
    <h1 data-translate="wantReceipt"></h1>
    <div class="yesReceipt">
        <form action="{{ url_for('bePatientReceipt.bePatientReceipt', bankpas_id=bankpas_id) }}" method="GET">
            <button data-translate="yes" type="submit"></button>
        </form>
    </div>
    <div class="noReceipt">
        <form action="{{ url_for('goodBye.goodBye') }}" method="GET">
            <button data-translate="no" type="submit"></button>
        </form>
    </div>
</body>
</html>